(function(){
  const styleId='byelingua-shared-header-style';
  if(!document.getElementById(styleId)){
    const style=document.createElement('style');style.id=styleId;style.textContent=`
      .byelingua-compact-header{position:sticky;top:0;z-index:40;border-bottom:1px solid #d7d7ce;background:rgba(245,242,233,.97);backdrop-filter:blur(8px)}
      .byelingua-compact-inner{width:min(1120px,calc(100% - 28px));min-height:52px;margin:auto;display:flex;align-items:center;gap:16px}
      .byelingua-compact-brand{color:#214d3a;font:600 25px/.95 Georgia,serif;text-decoration:none;letter-spacing:-.025em}
      .byelingua-compact-tagline{color:#68716b;font-size:10px;letter-spacing:.08em;white-space:nowrap}
      .byelingua-compact-spacer{flex:1}.byelingua-compact-actions{display:flex;align-items:center;gap:6px;flex-wrap:wrap}
      .byelingua-compact-actions button{font:inherit;cursor:pointer;border:1px solid #aebbb2;border-radius:4px;padding:6px 9px;background:transparent;color:#214d3a}
      .byelingua-compact-actions button.active{background:#214d3a;color:#fff;border-color:#214d3a}
      .schedule-site-header.byelingua-compact-header{width:100%;padding:0;border-bottom:0}.schedule-site-header.byelingua-compact-header .schedule-identity{display:flex;align-items:center;gap:14px}.schedule-site-header.byelingua-compact-header .schedule-brand{font-size:25px}.schedule-site-header.byelingua-compact-header .schedule-tagline{margin:0}.schedule-site-header.byelingua-compact-header .schedule-page-title,.schedule-site-header.byelingua-compact-header .schedule-page-description{display:none}.schedule-page-heading{width:min(1120px,calc(100% - 28px));margin:18px auto 2px}.schedule-page-heading h1{margin:0;color:#214d3a}.schedule-page-heading .hint{margin-top:3px}
      .byelingua-compact-account{color:#68716b;font-size:12px;max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:700px){.byelingua-compact-inner{min-height:48px;gap:8px}.byelingua-compact-tagline{display:none}.byelingua-compact-brand{font-size:22px}.byelingua-compact-actions button{min-height:36px;padding:5px 7px}.schedule-site-header.byelingua-compact-header .schedule-identity{width:auto}.schedule-site-header.byelingua-compact-header .schedule-tagline{display:none}}
    `;document.head.append(style)
  }
  window.ByelinguaHeader={mount:function(target,options){if(!target)return;options=options||{};const i18n=window.ByelinguaI18n;target.classList.add('byelingua-compact-header');target.innerHTML='<div class="byelingua-compact-inner"><a class="byelingua-compact-brand" href="/" aria-label="Byelingua home">BYELINGUA</a><span class="byelingua-compact-tagline">SO MANY COUNTRIES. SO MANY LANGUAGES. I SIMPLY CAN’T.</span><span class="byelingua-compact-spacer"></span><div class="byelingua-compact-actions"><span id="accountLabel" hidden></span><button id="accountButton" type="button" data-shared-account></button><button id="logoutButton" type="button" data-shared-signout></button><button type="button" data-shared-language="zh">中文</button><button type="button" data-shared-language="en">English</button></div></div>';const render=()=>{const language=i18n?i18n.getUiLanguage():(localStorage.getItem('byelinguaUiLanguage')||'zh');target.querySelector('[data-shared-account]').textContent=language==='en'?'User Center':'用户中心';target.querySelector('[data-shared-signout]').textContent=language==='en'?'Sign out':'退出登录';target.querySelectorAll('[data-shared-language]').forEach(button=>button.classList.toggle('active',button.dataset.sharedLanguage===language));document.documentElement.lang=language==='en'?'en-GB':'zh-CN'};target.querySelectorAll('[data-shared-language]').forEach(button=>button.onclick=()=>{localStorage.setItem('byelinguaUiLanguage',button.dataset.sharedLanguage);window.dispatchEvent(new CustomEvent('byelingua-language-change',{detail:button.dataset.sharedLanguage}));render()});target.querySelector('[data-shared-account]').onclick=()=>location.href='/account.html';target.querySelector('[data-shared-signout]').onclick=async()=>{try{const cfg=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'get_auth_config'})}).then(r=>r.json());if(window.supabase){const client=window.supabase.createClient(cfg.url,cfg.publishable_key);await client.auth.signOut()}}finally{location.href='/'}};render();window.addEventListener('byelingua-language-change',render);return target}};
})();
