-- FINAL STABILIZATION PRODUCTION SQL; DO NOT EXECUTE IN THIS TASK.
BEGIN;
DO $$ DECLARE n integer; BEGIN
 IF (SELECT count(*) FROM public.organizations WHERE slug='opera-national-de-paris')<>1 THEN RAISE EXCEPTION 'Paris Opera organization must resolve exactly once'; END IF;
 SELECT count(*) INTO n FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris'; IF n<>506 THEN RAISE EXCEPTION 'Paris Events baseline: %',n; END IF;
 IF (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='Ballet')<>207 OR (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='Concert et Récital')<>43 OR (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='Jeune Public')<>69 OR (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='Opéra')<>177 OR (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='Rencontre')<>1 OR (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='Répétition')<>9 THEN RAISE EXCEPTION 'Paris French counts changed'; END IF;
 IF EXISTS (SELECT 1 FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND (e.event_type IS NULL OR e.event_type NOT IN ('Ballet','Concert et Récital','Jeune Public','Opéra','Rencontre','Répétition'))) THEN RAISE EXCEPTION 'Paris NULL/unexpected value'; END IF;
END $$;
UPDATE public.events e SET event_type=CASE e.event_type WHEN 'Ballet' THEN 'ballet' WHEN 'Concert et Récital' THEN 'concert_recital' WHEN 'Jeune Public' THEN 'young_audience' WHEN 'Opéra' THEN 'opera' WHEN 'Rencontre' THEN 'encounter' WHEN 'Répétition' THEN 'rehearsal' END FROM public.organizations o WHERE o.id=e.organization_id AND o.slug='opera-national-de-paris' AND e.event_type IN ('Ballet','Concert et Récital','Jeune Public','Opéra','Rencontre','Répétition');
DO $$ BEGIN
 IF (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris')<>506 THEN RAISE EXCEPTION 'Paris post Event count changed'; END IF;
 IF EXISTS (SELECT 1 FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND (e.event_type IS NULL OR e.event_type NOT IN ('ballet','concert_recital','young_audience','opera','encounter','rehearsal'))) THEN RAISE EXCEPTION 'Paris post NULL/unexpected value'; END IF;
 IF (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='ballet')<>207 OR (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='concert_recital')<>43 OR (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='young_audience')<>69 OR (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='opera')<>177 OR (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='encounter')<>1 OR (SELECT count(*) FROM public.events e JOIN public.organizations o ON o.id=e.organization_id WHERE o.slug='opera-national-de-paris' AND e.event_type='rehearsal')<>9 THEN RAISE EXCEPTION 'Paris post counts changed'; END IF;
END $$;
COMMIT;
